"""dotspy - A Pythonic wrapper for Graphviz DOT language."""

from .builtin_styles import (
    BIDIRECTIONAL,
    BLUE_EDGE,
    BOLD_EDGE,
    BOX_NODE,
    CIRCLE_NODE,
    COMPACT_GRAPH,
    DASHED_EDGE,
    DECISION_NODE,
    DIAMOND_NODE,
    DOTTED_EDGE,
    GREEN_EDGE,
    INVISIBLE_NODE,
    LR_GRAPH,
    NO_ARROW,
    PROCESS_NODE,
    RECORD_NODE,
    RED_EDGE,
    ROUNDED_BOX,
    SPACED_GRAPH,
    TB_GRAPH,
    TERMINAL_NODE,
)
from .constants import *
from .context import get_graph, set_graph

# Diagram-specific components
from .diagrams import (
    MINDMAP_GRAPH,
    RADIAL_MINDMAP_GRAPH,
    UML_GRAPH,
    AbstractClassNode,
    AggregationEdge,
    AssociationEdge,
    BranchEdge,
    BranchNode,
    ClassNode,
    CompositionEdge,
    DependencyEdge,
    DiagramEdge,
    DiagramNode,
    ImplementsEdge,
    InheritanceEdge,
    InterfaceNode,
    LeafNode,
    MindNode,
    NoteEdge,
    NoteNode,
    TopicNode,
)
from .edge import Edge
from .graph import Graph, Subgraph
from .node import HTMLNode, Node
from .style import EdgeStyle, GraphStyle, NodeStyle
from .utils import render_to_file, render_to_svg

__version__ = "0.1.0"
__all__ = [
    # Core classes
    "Node",
    "HTMLNode",
    "Edge",
    "Graph",
    "Subgraph",
    # Style classes
    "NodeStyle",
    "EdgeStyle",
    "GraphStyle",
    # Singleton functions
    "set_graph",
    "get_graph",
    # Utility functions
    "render_to_file",
    "render_to_svg",
    # Constants
    "RECT",
    "BOX",
    "CIRCLE",
    "ELLIPSE",
    "DIAMOND",
    "PLAINTEXT",
    "POINT",
    "RECORD",
    "POLYGON",
    "TRIANGLE",
    "SQUARE",
    "STAR",
    "FILLED",
    "SOLID",
    "DASHED",
    "DOTTED",
    "BOLD",
    "ROUNDED",
    "INVISIBLE",
    "RED",
    "BLUE",
    "GREEN",
    "BLACK",
    "WHITE",
    "GRAY",
    "YELLOW",
    "ORANGE",
    "PURPLE",
    "CYAN",
    "MAGENTA",
    "LIGHTBLUE",
    "LIGHTGRAY",
    "DARKGRAY",
    "DIGRAPH",
    "GRAPH",
    "TB",
    "BT",
    "LR",
    "RL",
    "NORMAL",
    "NONE",
    "VEE",
    "DIAMOND_ARROW",
    "DOT_ARROW",
    "OPEN",
    "BOX_ARROW",
    "HELVETICA",
    "TIMES",
    "COURIER",
    # Builtin styles
    "BOX_NODE",
    "ROUNDED_BOX",
    "CIRCLE_NODE",
    "DIAMOND_NODE",
    "RECORD_NODE",
    "DECISION_NODE",
    "PROCESS_NODE",
    "TERMINAL_NODE",
    "INVISIBLE_NODE",
    "DASHED_EDGE",
    "DOTTED_EDGE",
    "BOLD_EDGE",
    "RED_EDGE",
    "BLUE_EDGE",
    "GREEN_EDGE",
    "NO_ARROW",
    "BIDIRECTIONAL",
    "LR_GRAPH",
    "TB_GRAPH",
    "COMPACT_GRAPH",
    "SPACED_GRAPH",
    # Diagram components
    "DiagramNode",
    "DiagramEdge",
    "ClassNode",
    "InterfaceNode",
    "AbstractClassNode",
    "InheritanceEdge",
    "ImplementsEdge",
    "CompositionEdge",
    "AggregationEdge",
    "AssociationEdge",
    "DependencyEdge",
    "UML_GRAPH",
    "MindNode",
    "NoteNode",
    "NoteEdge",
    "TopicNode",  # Backward compatibility
    "BranchNode",  # Backward compatibility
    "LeafNode",  # Backward compatibility
    "BranchEdge",
    "MINDMAP_GRAPH",
    "RADIAL_MINDMAP_GRAPH",
]
